title: Ne0's blog
description: Good defense requires a detailed knowledge of offense.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
author: Ne0

home: /index.html
github:
    homepage: https://github.com/Changochen

about: /about.html

friends: /friendlink.html
